import { Factory } from '@/interfaces/planner/FactoryInterface'

export const demoFactories: Factory[] = [{
  id: 844,
  name: 'Oil Processing',
  products: [{
    id: 'Plastic',
    amount: 640,
    recipe: 'Plastic',
    displayOrder: 0,
    requirements: { LiquidOil: { amount: 1920 } },
    buildingRequirements: { name: 'oilrefinery', amount: 32.000, powerPerBuilding: 45, totalPower: 1440.00 },
    byProducts: [{ id: 'HeavyOilResidue', byProductOf: 'Plastic', amount: 320 }],
  }, {
    id: 'LiquidFuel',
    amount: 40,
    recipe: 'ResidualFuel',
    displayOrder: 1,
    requirements: { HeavyOilResidue: { amount: 240 } },
    buildingRequirements: { name: 'oilrefinery', amount: 1.000, powerPerBuilding: 7.5, totalPower: 7.00 },
    byProducts: [],
  }],
  byProducts: [{ id: 'HeavyOilResidue', amount: 320, byProductOf: 'Plastic' }],
  internalProducts: {},
  inputs: [],
  parts: {
    Plastic: {
      amountRequired: 0,
      amountSupplied: 640,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 640,
      amountRemaining: -640,
      satisfied: true,
      isRaw: false,
    },
    LiquidOil: {
      amountRequired: 1920,
      amountSupplied: 1920,
      amountSuppliedViaInput: 1920,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: true,
    },
    LiquidFuel: {
      amountRequired: 0,
      amountSupplied: 40,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 40,
      amountRemaining: -40,
      satisfied: true,
      isRaw: false,
    },
    HeavyOilResidue: {
      amountRequired: 240,
      amountSupplied: 320,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 320,
      amountRemaining: -80,
      satisfied: true,
      isRaw: false,
    },
  },
  buildingRequirements: { oilrefinery: { name: 'oilrefinery', amount: 33, powerPerBuilding: 45, totalPower: 1447 } },
  requirementsSatisfied: true,
  totalPower: 1447,
  dependencies: {
    requests: { 1892: [{ part: 'Plastic', amount: 320 }], 4954: [{ part: 'Plastic', amount: 320 }] },
    metrics: { Plastic: { part: 'Plastic', request: 640, supply: 640, isRequestSatisfied: true, difference: 0 } },
  },
  exportCalculator: {
    LiquidFuel: {
      selected: '4954',
      factorySettings: { 1892: { trainTime: 123 }, 4954: { trainTime: 123 }, 6276: { trainTime: 123 } },
    },
    PolymerResin: { selected: null, factorySettings: { 6276: { trainTime: 123 } } },
    Plastic: { selected: '4954', factorySettings: { 1892: { trainTime: 123 }, 4954: { trainTime: 123 } } },
    HeavyOilResidue: { selected: '1892', factorySettings: { 1892: { trainTime: 123 }, 4954: { trainTime: 123 } } },
  },
  rawResources: { LiquidOil: { id: 'LiquidOil', name: 'Crude Oil', amount: 1920 } },
  usingRawResourcesOnly: false,
  surplus: { Plastic: { amount: 640 }, LiquidFuel: { amount: 40 }, HeavyOilResidue: { amount: 80 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 0,
}, {
  id: 4394,
  name: 'Copper Ingots',
  products: [{
    id: 'CopperIngot',
    amount: 640,
    recipe: 'IngotCopper',
    displayOrder: 0,
    requirements: { OreCopper: { amount: 640 } },
    buildingRequirements: { name: 'smeltermk1', amount: 21.333, powerPerBuilding: 4, totalPower: 84.00 },
    byProducts: [],
  }],
  byProducts: [],
  internalProducts: {},
  inputs: [],
  parts: {
    CopperIngot: {
      amountRequired: 0,
      amountSupplied: 640,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 640,
      amountRemaining: -640,
      satisfied: true,
      isRaw: false,
    },
    OreCopper: {
      amountRequired: 640,
      amountSupplied: 640,
      amountSuppliedViaInput: 640,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: true,
    },
  },
  buildingRequirements: { smeltermk1: { name: 'smeltermk1', amount: 21.333, powerPerBuilding: 4, totalPower: 84 } },
  requirementsSatisfied: true,
  totalPower: 84,
  dependencies: {
    requests: { 466: [{ part: 'CopperIngot', amount: 320 }], 3415: [{ part: 'CopperIngot', amount: 320 }] },
    metrics: { CopperIngot: { part: 'CopperIngot', request: 640, supply: 640, isRequestSatisfied: true, difference: 0 } },
  },
  exportCalculator: { CopperIngot: { selected: '466', factorySettings: { 466: { trainTime: 123 }, 3415: { trainTime: 123 } } } },
  rawResources: { OreCopper: { id: 'OreCopper', name: 'Copper Ore', amount: 640 } },
  usingRawResourcesOnly: true,
  surplus: { CopperIngot: { amount: 640 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 1,
}, {
  id: 466,
  name: 'Copper Basics',
  products: [{
    id: 'Wire',
    amount: 320,
    recipe: 'Wire',
    displayOrder: 0,
    requirements: { CopperIngot: { amount: 320 } },
    buildingRequirements: { name: 'constructormk1', amount: 10.667, powerPerBuilding: 2, totalPower: 20.00 },
    byProducts: [],
  }, {
    id: 'Cable',
    amount: 160,
    recipe: 'Cable',
    displayOrder: 1,
    requirements: { Wire: { amount: 320 } },
    buildingRequirements: { name: 'constructormk1', amount: 5.333, powerPerBuilding: 4, totalPower: 20.00 },
    byProducts: [],
  }],
  byProducts: [],
  internalProducts: { Wire: { id: 'Wire', amount: 320 } },
  inputs: [{ factoryId: 4394, outputPart: 'CopperIngot', amount: 320 }],
  parts: {
    CopperIngot: {
      amountRequired: 320,
      amountSupplied: 320,
      amountSuppliedViaInput: 320,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    Wire: {
      amountRequired: 320,
      amountSupplied: 320,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 320,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    Cable: {
      amountRequired: 0,
      amountSupplied: 160,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 160,
      amountRemaining: -160,
      satisfied: true,
      isRaw: false,
    },
  },
  buildingRequirements: { constructormk1: { name: 'constructormk1', amount: 16, powerPerBuilding: 2, totalPower: 40 } },
  requirementsSatisfied: true,
  totalPower: 40,
  dependencies: {
    requests: { 1892: [{ part: 'Cable', amount: 160 }] },
    metrics: { Cable: { part: 'Cable', request: 160, supply: 160, isRequestSatisfied: true, difference: 0 } },
  },
  exportCalculator: {
    Wire: { selected: '1892', factorySettings: { 1892: { trainTime: 123 } } },
    Cable: { selected: '1892', factorySettings: { 1892: { trainTime: 123 } } },
  },
  rawResources: {},
  usingRawResourcesOnly: false,
  surplus: { Cable: { amount: 160 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 2,
}, {
  id: 3415,
  name: 'Copper Sheets',
  products: [{
    id: 'CopperSheet',
    amount: 160,
    recipe: 'CopperSheet',
    displayOrder: 0,
    requirements: { CopperIngot: { amount: 320 } },
    buildingRequirements: { name: 'constructormk1', amount: 16.000, powerPerBuilding: 4, totalPower: 64.00 },
    byProducts: [],
  }],
  byProducts: [],
  internalProducts: {},
  inputs: [{ factoryId: 4394, outputPart: 'CopperIngot', amount: 320 }],
  parts: {
    CopperIngot: {
      amountRequired: 320,
      amountSupplied: 320,
      amountSuppliedViaInput: 320,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    CopperSheet: {
      amountRequired: 0,
      amountSupplied: 160,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 160,
      amountRemaining: -160,
      satisfied: true,
      isRaw: false,
    },
  },
  buildingRequirements: { constructormk1: { name: 'constructormk1', amount: 16, powerPerBuilding: 4, totalPower: 64 } },
  requirementsSatisfied: true,
  totalPower: 64,
  dependencies: {
    requests: { 4954: [{ part: 'CopperSheet', amount: 160 }] },
    metrics: { CopperSheet: { part: 'CopperSheet', request: 160, supply: 160, isRequestSatisfied: true, difference: 0 } },
  },
  exportCalculator: { CopperSheet: { selected: '4954', factorySettings: { 4954: { trainTime: 123 } } } },
  rawResources: {},
  usingRawResourcesOnly: false,
  surplus: { CopperSheet: { amount: 160 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 3,
}, {
  id: 4954,
  name: 'Circuit Boards',
  products: [{
    id: 'CircuitBoard',
    amount: 80,
    recipe: 'CircuitBoard',
    displayOrder: 0,
    requirements: { CopperSheet: { amount: 160 }, Plastic: { amount: 320 } },
    buildingRequirements: { name: 'assemblermk1', amount: 10.667, powerPerBuilding: 15, totalPower: 150.00 },
    byProducts: [],
  }],
  byProducts: [],
  internalProducts: {},
  inputs: [{ factoryId: 844, outputPart: 'Plastic', amount: 320 }, {
    factoryId: 3415,
    outputPart: 'CopperSheet',
    amount: 160,
  }],
  parts: {
    Plastic: {
      amountRequired: 320,
      amountSupplied: 320,
      amountSuppliedViaInput: 320,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    CopperSheet: {
      amountRequired: 160,
      amountSupplied: 160,
      amountSuppliedViaInput: 160,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    CircuitBoard: {
      amountRequired: 0,
      amountSupplied: 80,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 80,
      amountRemaining: -80,
      satisfied: true,
      isRaw: false,
    },
  },
  buildingRequirements: {
    assemblermk1: {
      name: 'assemblermk1',
      amount: 10.667,
      powerPerBuilding: 15,
      totalPower: 150,
    },
  },
  requirementsSatisfied: true,
  totalPower: 150,
  dependencies: {
    requests: { 1892: [{ part: 'CircuitBoard', amount: 80 }] },
    metrics: { CircuitBoard: { part: 'CircuitBoard', request: 80, supply: 80, isRequestSatisfied: true, difference: 0 } },
  },
  exportCalculator: { CircuitBoard: { selected: '1892', factorySettings: { 1892: { trainTime: 123 } } } },
  rawResources: {},
  usingRawResourcesOnly: false,
  surplus: { CircuitBoard: { amount: 80 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 4,
}, {
  id: 1892,
  name: 'Computers (end product)',
  products: [{
    id: 'Computer',
    amount: 20,
    recipe: 'Computer',
    displayOrder: 0,
    requirements: { CircuitBoard: { amount: 80 }, Cable: { amount: 160 }, Plastic: { amount: 320 } },
    buildingRequirements: { name: 'manufacturermk1', amount: 8.000, powerPerBuilding: 55, totalPower: 440.00 },
    byProducts: [],
  }],
  byProducts: [],
  internalProducts: {},
  inputs: [{ factoryId: 466, outputPart: 'Cable', amount: 160 }, {
    factoryId: 4954,
    outputPart: 'CircuitBoard',
    amount: 80,
  }, { factoryId: 844, outputPart: 'Plastic', amount: 320 }],
  parts: {
    Cable: {
      amountRequired: 160,
      amountSupplied: 160,
      amountSuppliedViaInput: 160,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    CircuitBoard: {
      amountRequired: 80,
      amountSupplied: 80,
      amountSuppliedViaInput: 80,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    Plastic: {
      amountRequired: 320,
      amountSupplied: 320,
      amountSuppliedViaInput: 320,
      amountSuppliedViaProduction: 0,
      amountRemaining: 0,
      satisfied: true,
      isRaw: false,
    },
    Computer: {
      amountRequired: 0,
      amountSupplied: 20,
      amountSuppliedViaInput: 0,
      amountSuppliedViaProduction: 20,
      amountRemaining: -20,
      satisfied: true,
      isRaw: false,
    },
  },
  buildingRequirements: {
    manufacturermk1: {
      name: 'manufacturermk1',
      amount: 8,
      powerPerBuilding: 55,
      totalPower: 440,
    },
  },
  requirementsSatisfied: true,
  totalPower: 440,
  dependencies: { requests: {}, metrics: {} },
  exportCalculator: { Computer: { selected: null, factorySettings: {} } },
  rawResources: {},
  usingRawResourcesOnly: false,
  surplus: { Computer: { amount: 20 } },
  hidden: false,
  hasProblem: false,
  displayOrder: 5,
}]
