// This scenario contains a factory that has various errors, namely missing keys and whatnot.
// This is effectively a mishmash of 0.2 and 0.3 data.
// This is therefore a great candidate to test current and figure migrations on.
export const create317Scenario = () => {
  return [{
    id: 5257,
    name: 'Iron Plate | Rod | Screw',
    products: [{
      id: 'IronPlate',
      amount: 60,
      recipe: 'IronPlate',
      displayOrder: 0,
      requirements: { IronIngot: { amount: 90 } },
      buildingRequirements: { name: 'constructormk1', amount: 3, powerPerBuilding: 4, totalPower: 12 },
      byProducts: [],
    }, {
      id: 'IronRod',
      amount: 30,
      recipe: 'IronRod',
      displayOrder: 1,
      requirements: { IronIngot: { amount: 30 } },
      buildingRequirements: { name: 'constructormk1', amount: 2, powerPerBuilding: 4, totalPower: 8 },
      byProducts: [],
    }, {
      id: 'IronScrew',
      amount: 40,
      recipe: 'Screw',
      displayOrder: 2,
      requirements: { IronRod: { amount: 10 } },
      buildingRequirements: { name: 'constructormk1', amount: 1, powerPerBuilding: 4, totalPower: 4 },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 120,
      recipe: 'IngotIron',
      displayOrder: 3,
      requirements: { OreIron: { amount: 120 } },
      buildingRequirements: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 16 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: { IronIngot: { id: 'IronIngot', amount: 120 }, IronRod: { id: 'IronRod', amount: 30 } },
    inputs: [],
    parts: {
      IronPlate: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 60,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 60,
        amountRemaining: 60,
        satisfied: true,
        isRaw: false,
      },
      IronIngot: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 120,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronRod: {
        amountRequired: 10,
        amountRequiredExports: 0,
        amountRequiredProduction: 10,
        amountSupplied: 30,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 30,
        amountRemaining: 20,
        satisfied: true,
        isRaw: false,
      },
      IronScrew: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 40,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 40,
        amountRemaining: 40,
        satisfied: true,
        isRaw: false,
      },
      OreIron: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      constructormk1: {
        name: 'constructormk1',
        amount: 6,
        powerPerBuilding: 4,
        totalPower: 24,
      },
      smeltermk1: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 40 },
    },
    totalPower: 40,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {
      IronPlate: { selected: null, factorySettings: {} },
      IronRod: { selected: null, factorySettings: {} },
      IronScrew: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
    },
    rawResources: { OreIron: { id: 'OreIron', name: 'Iron Ore', amount: 120 } },
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 120, displayOrder: 3 },
      IronScrew: { productId: 'IronScrew', surplus: 40, demands: 0, supply: 40, displayOrder: 2 },
      IronRod: { productId: 'IronRod', surplus: 20, demands: 0, supply: 30, displayOrder: 1 },
      IronPlate: { productId: 'IronPlate', surplus: 60, demands: 0, supply: 60, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 0,
    inSync: true,
    syncState: {
      IronPlate: { amount: 60, recipe: 'IronPlate' },
      IronRod: { amount: 30, recipe: 'IronRod' },
      IronScrew: { amount: 40, recipe: 'Screw' },
      IronIngot: { amount: 120, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 8835,
    name: 'Reinforced Ironplate',
    products: [{
      id: 'IronPlateReinforced',
      amount: 10,
      recipe: 'IronPlateReinforced',
      displayOrder: 0,
      requirements: { IronPlate: { amount: 60 }, IronScrew: { amount: 120 } },
      buildingRequirements: { name: 'assemblermk1', amount: 2, powerPerBuilding: 15, totalPower: 30 },
      byProducts: [],
    }, {
      id: 'IronPlate',
      amount: 60,
      recipe: 'IronPlate',
      displayOrder: 1,
      requirements: { IronIngot: { amount: 90 } },
      buildingRequirements: { name: 'constructormk1', amount: 3, powerPerBuilding: 4, totalPower: 12 },
      byProducts: [],
    }, {
      id: 'IronScrew',
      amount: 120,
      recipe: 'Screw',
      displayOrder: 2,
      requirements: { IronRod: { amount: 30 } },
      buildingRequirements: { name: 'constructormk1', amount: 3, powerPerBuilding: 4, totalPower: 12 },
      byProducts: [],
    }, {
      id: 'IronRod',
      amount: 30,
      recipe: 'IronRod',
      displayOrder: 3,
      requirements: { IronIngot: { amount: 30 } },
      buildingRequirements: { name: 'constructormk1', amount: 2, powerPerBuilding: 4, totalPower: 8 },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 120,
      recipe: 'IngotIron',
      displayOrder: 4,
      requirements: { OreIron: { amount: 120 } },
      buildingRequirements: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 16 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      IronPlate: { id: 'IronPlate', amount: 60 },
      IronScrew: { id: 'IronScrew', amount: 120 },
      IronIngot: { id: 'IronIngot', amount: 120 },
      IronRod: { id: 'IronRod', amount: 30 },
    },
    inputs: [],
    parts: {
      IronPlateReinforced: {
        amountRequired: 2,
        amountRequiredExports: 2,
        amountRequiredProduction: 0,
        amountSupplied: 10,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 10,
        amountRemaining: 8,
        satisfied: true,
        isRaw: false,
      },
      IronPlate: {
        amountRequired: 60,
        amountRequiredExports: 0,
        amountRequiredProduction: 60,
        amountSupplied: 60,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 60,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronScrew: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 120,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronIngot: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 120,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronRod: {
        amountRequired: 30,
        amountRequiredExports: 0,
        amountRequiredProduction: 30,
        amountSupplied: 30,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 30,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreIron: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 2,
        powerPerBuilding: 15,
        totalPower: 30,
      },
      constructormk1: { name: 'constructormk1', amount: 8, powerPerBuilding: 4, totalPower: 62 },
      smeltermk1: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 78 },
    },
    totalPower: 78,
    dependencies: {
      requests: { 8871: [{ requestingFactoryId: 8871, part: 'IronPlateReinforced', amount: 2 }] },
      metrics: {
        IronPlateReinforced: {
          part: 'IronPlateReinforced',
          request: 2,
          supply: 10,
          isRequestSatisfied: true,
          difference: 8,
        },
      },
    },
    exportCalculator: {
      IronPlateReinforced: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
      IronRod: { selected: null, factorySettings: {} },
      IronScrew: { selected: null, factorySettings: {} },
      IronPlate: { selected: null, factorySettings: {} },
    },
    rawResources: { OreIron: { id: 'OreIron', name: 'Iron Ore', amount: 120 } },
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 120, displayOrder: 4 },
      IronRod: { productId: 'IronRod', surplus: 0, demands: 0, supply: 30, displayOrder: 3 },
      IronScrew: { productId: 'IronScrew', surplus: 0, demands: 0, supply: 120, displayOrder: 2 },
      IronPlate: { productId: 'IronPlate', surplus: 0, demands: 0, supply: 60, displayOrder: 1 },
      IronPlateReinforced: {
        productId: 'IronPlateReinforced',
        surplus: 8,
        demands: 2,
        supply: 10,
        displayOrder: 0,
      },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 1,
    inSync: true,
    syncState: {
      IronPlateReinforced: { amount: 10, recipe: 'IronPlateReinforced' },
      IronPlate: { amount: 60, recipe: 'IronPlate' },
      IronScrew: { amount: 120, recipe: 'Screw' },
      IronRod: { amount: 30, recipe: 'IronRod' },
      IronIngot: { amount: 120, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 3612,
    name: 'Rotor',
    products: [{
      id: 'Rotor',
      amount: 10,
      recipe: 'Rotor',
      displayOrder: 0,
      requirements: { IronRod: { amount: 50 }, IronScrew: { amount: 250 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 2.5,
        powerPerBuilding: 15,
        totalPower: 36.00000039462546,
      },
      byProducts: [],
    }, {
      id: 'IronScrew',
      amount: 250,
      recipe: 'Screw',
      displayOrder: 1,
      requirements: { IronRod: { amount: 62.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 6.25,
        powerPerBuilding: 4,
        totalPower: 24.640000084186767,
      },
      byProducts: [],
    }, {
      id: 'IronRod',
      amount: 112.5,
      recipe: 'IronRod',
      displayOrder: 2,
      requirements: { IronIngot: { amount: 112.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 7.5,
        powerPerBuilding: 4,
        totalPower: 29.600000105233455,
      },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 112.5,
      recipe: 'IngotIron',
      displayOrder: 3,
      requirements: { OreIron: { amount: 112.5 } },
      buildingRequirements: {
        name: 'smeltermk1',
        amount: 3.75,
        powerPerBuilding: 4,
        totalPower: 14.73463883584809,
      },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      IronRod: { id: 'IronRod', amount: 112.5 },
      IronScrew: { id: 'IronScrew', amount: 250 },
      IronIngot: { id: 'IronIngot', amount: 112.5 },
    },
    inputs: [],
    parts: {
      Rotor: {
        amountRequired: 2,
        amountRequiredExports: 2,
        amountRequiredProduction: 0,
        amountSupplied: 10,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 10,
        amountRemaining: 8,
        satisfied: true,
        isRaw: false,
      },
      IronRod: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 112.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronScrew: {
        amountRequired: 250,
        amountRequiredExports: 0,
        amountRequiredProduction: 250,
        amountSupplied: 250,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 250,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronIngot: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 112.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreIron: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 112.5,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 2.5,
        powerPerBuilding: 15,
        totalPower: 36.00000039462546,
      },
      constructormk1: {
        name: 'constructormk1',
        amount: 13.75,
        powerPerBuilding: 4,
        totalPower: 90.24000058404567,
      },
      smeltermk1: { name: 'smeltermk1', amount: 3.75, powerPerBuilding: 4, totalPower: 104.97463941989376 },
    },
    totalPower: 104.97463941989376,
    dependencies: {
      requests: { 8871: [{ requestingFactoryId: 8871, part: 'Rotor', amount: 2 }] },
      metrics: { Rotor: { part: 'Rotor', request: 2, supply: 10, isRequestSatisfied: true, difference: 8 } },
    },
    exportCalculator: {
      Rotor: { selected: null, factorySettings: {} },
      SpaceElevatorPart_5: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
      IronRod: { selected: null, factorySettings: {} },
      IronScrew: { selected: null, factorySettings: {} },
    },
    rawResources: { OreIron: { id: 'OreIron', name: 'Iron Ore', amount: 112.5 } },
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 112.5, displayOrder: 3 },
      IronRod: { productId: 'IronRod', surplus: 0, demands: 0, supply: 112.5, displayOrder: 2 },
      IronScrew: { productId: 'IronScrew', surplus: 0, demands: 0, supply: 250, displayOrder: 1 },
      Rotor: { productId: 'Rotor', surplus: 8, demands: 2, supply: 10, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 2,
    inSync: true,
    syncState: {
      Rotor: { amount: 10, recipe: 'Rotor' },
      IronScrew: { amount: 250, recipe: 'Screw' },
      IronRod: { amount: 112.5, recipe: 'IronRod' },
      IronIngot: { amount: 112.5, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 8871,
    name: 'Smart Plating',
    products: [{
      id: 'SpaceElevatorPart_1',
      amount: 2,
      recipe: 'SpaceElevatorPart_1',
      displayOrder: 0,
      requirements: { IronPlateReinforced: { amount: 2 }, Rotor: { amount: 2 } },
      buildingRequirements: { name: 'assemblermk1', amount: 1, powerPerBuilding: 15, totalPower: 15 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {},
    inputs: [{ factoryId: 8835, outputPart: 'IronPlateReinforced', amount: 2 }, {
      factoryId: 3612,
      outputPart: 'Rotor',
      amount: 2,
    }],
    parts: {
      IronPlateReinforced: {
        amountRequired: 2,
        amountRequiredExports: 0,
        amountRequiredProduction: 2,
        amountSupplied: 2,
        amountSuppliedViaInput: 2,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Rotor: {
        amountRequired: 2,
        amountRequiredExports: 0,
        amountRequiredProduction: 2,
        amountSupplied: 2,
        amountSuppliedViaInput: 2,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      SpaceElevatorPart_1: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 2,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 2,
        amountRemaining: 2,
        satisfied: true,
        isRaw: false,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 1,
        powerPerBuilding: 15,
        totalPower: 15,
      },
    },
    totalPower: 15,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: { SpaceElevatorPart_1: { selected: null, factorySettings: {} } },
    rawResources: {},
    exports: {
      SpaceElevatorPart_1: {
        productId: 'SpaceElevatorPart_1',
        surplus: 2,
        demands: 0,
        supply: 2,
        displayOrder: 0,
      },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 3,
    inSync: true,
    syncState: { SpaceElevatorPart_1: { amount: 2, recipe: 'SpaceElevatorPart_1' } },
    tasks: [],
    notes: '',
  }, {
    id: 2161,
    name: 'Concrete',
    products: [{
      id: 'Cement',
      amount: 40,
      recipe: 'Concrete',
      displayOrder: 0,
      requirements: { Stone: { amount: 120 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 2.6666666666666665,
        powerPerBuilding: 4,
        totalPower: 10.340345765969857,
      },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {},
    inputs: [],
    parts: {
      Cement: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 40,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 40,
        amountRemaining: 40,
        satisfied: true,
        isRaw: false,
      },
      Stone: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      constructormk1: {
        name: 'constructormk1',
        amount: 2.6666666666666665,
        powerPerBuilding: 4,
        totalPower: 10.340345765969857,
      },
    },
    totalPower: 10.340345765969857,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: { Cement: { selected: null, factorySettings: {} } },
    rawResources: { Stone: { id: 'Stone', name: 'Limestone', amount: 120 } },
    exports: { Cement: { productId: 'Cement', surplus: 40, demands: 0, supply: 40, displayOrder: 0 } },
    requirementsSatisfied: true,
    usingRawResourcesOnly: true,
    hidden: true,
    hasProblem: false,
    displayOrder: 4,
    inSync: true,
    syncState: { Cement: { amount: 40, recipe: 'Concrete' } },
    tasks: [],
    notes: '',
  }, {
    id: 6529,
    name: 'Copper Sheets | Wire | Cable',
    products: [{
      id: 'CopperSheet',
      amount: 30,
      recipe: 'CopperSheet',
      displayOrder: 0,
      requirements: { CopperIngot: { amount: 60 } },
      buildingRequirements: { name: 'constructormk1', amount: 3, powerPerBuilding: 4, totalPower: 12 },
      byProducts: [],
    }, {
      id: 'Cable',
      amount: 30,
      recipe: 'Cable',
      displayOrder: 1,
      requirements: { Wire: { amount: 60 } },
      buildingRequirements: { name: 'constructormk1', amount: 1, powerPerBuilding: 4, totalPower: 4 },
      byProducts: [],
    }, {
      id: 'Wire',
      amount: 60,
      recipe: 'Wire',
      displayOrder: 2,
      requirements: { CopperIngot: { amount: 30 } },
      buildingRequirements: { name: 'constructormk1', amount: 2, powerPerBuilding: 4, totalPower: 8 },
      byProducts: [],
    }, {
      id: 'CopperIngot',
      amount: 150,
      recipe: 'IngotCopper',
      displayOrder: 3,
      requirements: { OreCopper: { amount: 150 } },
      buildingRequirements: { name: 'smeltermk1', amount: 5, powerPerBuilding: 4, totalPower: 20 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: { CopperIngot: { id: 'CopperIngot', amount: 150 }, Wire: { id: 'Wire', amount: 60 } },
    inputs: [],
    parts: {
      CopperSheet: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 30,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 30,
        amountRemaining: 30,
        satisfied: true,
        isRaw: false,
      },
      CopperIngot: {
        amountRequired: 90,
        amountRequiredExports: 0,
        amountRequiredProduction: 90,
        amountSupplied: 150,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 150,
        amountRemaining: 60,
        satisfied: true,
        isRaw: false,
      },
      Cable: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 30,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 30,
        amountRemaining: 30,
        satisfied: true,
        isRaw: false,
      },
      Wire: {
        amountRequired: 60,
        amountRequiredExports: 0,
        amountRequiredProduction: 60,
        amountSupplied: 60,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 60,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreCopper: {
        amountRequired: 150,
        amountRequiredExports: 0,
        amountRequiredProduction: 150,
        amountSupplied: 150,
        amountSuppliedViaInput: 150,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      constructormk1: {
        name: 'constructormk1',
        amount: 6,
        powerPerBuilding: 4,
        totalPower: 24,
      },
      smeltermk1: { name: 'smeltermk1', amount: 5, powerPerBuilding: 4, totalPower: 44 },
    },
    totalPower: 44,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {
      CopperSheet: { selected: null, factorySettings: {} },
      Cable: { selected: null, factorySettings: {} },
      CopperIngot: { selected: null, factorySettings: {} },
      Wire: { selected: null, factorySettings: {} },
    },
    rawResources: { OreCopper: { id: 'OreCopper', name: 'Copper Ore', amount: 150 } },
    exports: {
      CopperIngot: {
        productId: 'CopperIngot',
        surplus: 60,
        demands: 0,
        supply: 150,
        displayOrder: 3,
      },
      Wire: { productId: 'Wire', surplus: 0, demands: 0, supply: 60, displayOrder: 2 },
      Cable: { productId: 'Cable', surplus: 30, demands: 0, supply: 30, displayOrder: 1 },
      CopperSheet: { productId: 'CopperSheet', surplus: 30, demands: 0, supply: 30, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 5,
    inSync: true,
    syncState: {
      CopperSheet: { amount: 30, recipe: 'CopperSheet' },
      Cable: { amount: 30, recipe: 'Cable' },
      Wire: { amount: 60, recipe: 'Wire' },
      CopperIngot: { amount: 150, recipe: 'IngotCopper' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 5073,
    name: 'Modular Frames',
    products: [{
      id: 'ModularFrame',
      amount: 5,
      recipe: 'ModularFrame',
      displayOrder: 0,
      requirements: { IronPlateReinforced: { amount: 7.5 }, IronRod: { amount: 30 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 2.5,
        powerPerBuilding: 15,
        totalPower: 36.00000039462546,
      },
      byProducts: [],
    }, {
      id: 'IronPlateReinforced',
      amount: 7.5,
      recipe: 'IronPlateReinforced',
      displayOrder: 1,
      requirements: { IronPlate: { amount: 45 }, IronScrew: { amount: 90 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 1.5,
        powerPerBuilding: 15,
        totalPower: 21.00000039462546,
      },
      byProducts: [],
    }, {
      id: 'IronRod',
      amount: 52.5,
      recipe: 'IronRod',
      displayOrder: 2,
      requirements: { IronIngot: { amount: 52.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 3.5,
        powerPerBuilding: 4,
        totalPower: 13.600000105233455,
      },
      byProducts: [],
    }, {
      id: 'IronPlate',
      amount: 45,
      recipe: 'IronPlate',
      displayOrder: 3,
      requirements: { IronIngot: { amount: 67.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 2.25,
        powerPerBuilding: 4,
        totalPower: 8.640000084186767,
      },
      byProducts: [],
    }, {
      id: 'IronScrew',
      amount: 90,
      recipe: 'Screw',
      displayOrder: 4,
      requirements: { IronRod: { amount: 22.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 2.25,
        powerPerBuilding: 4,
        totalPower: 8.640000084186767,
      },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 120,
      recipe: 'IngotIron',
      displayOrder: 5,
      requirements: { OreIron: { amount: 120 } },
      buildingRequirements: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 16 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      IronPlateReinforced: { id: 'IronPlateReinforced', amount: 7.5 },
      IronRod: { id: 'IronRod', amount: 52.5 },
      IronPlate: { id: 'IronPlate', amount: 45 },
      IronScrew: { id: 'IronScrew', amount: 90 },
      IronIngot: { id: 'IronIngot', amount: 120 },
    },
    inputs: [],
    parts: {
      ModularFrame: {
        amountRequired: 2.5,
        amountRequiredExports: 2.5,
        amountRequiredProduction: 0,
        amountSupplied: 5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 5,
        amountRemaining: 2.5,
        satisfied: true,
        isRaw: false,
      },
      IronPlateReinforced: {
        amountRequired: 7.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 7.5,
        amountSupplied: 7.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 7.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronRod: {
        amountRequired: 52.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 52.5,
        amountSupplied: 52.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 52.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronPlate: {
        amountRequired: 45,
        amountRequiredExports: 0,
        amountRequiredProduction: 45,
        amountSupplied: 45,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 45,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronScrew: {
        amountRequired: 90,
        amountRequiredExports: 0,
        amountRequiredProduction: 90,
        amountSupplied: 90,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 90,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronIngot: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 120,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreIron: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 4,
        powerPerBuilding: 15,
        totalPower: 57.00000078925092,
      },
      constructormk1: { name: 'constructormk1', amount: 8, powerPerBuilding: 4, totalPower: 87.8800010628579 },
      smeltermk1: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 103.8800010628579 },
    },
    totalPower: 103.8800010628579,
    dependencies: {
      requests: { 9463: [{ requestingFactoryId: 9463, part: 'ModularFrame', amount: 2.5 }] },
      metrics: {
        ModularFrame: {
          part: 'ModularFrame',
          request: 2.5,
          supply: 5,
          isRequestSatisfied: true,
          difference: 2.5,
        },
      },
    },
    exportCalculator: {
      ModularFrame: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
      IronScrew: { selected: null, factorySettings: {} },
      IronPlate: { selected: null, factorySettings: {} },
      IronRod: { selected: null, factorySettings: {} },
      IronPlateReinforced: { selected: null, factorySettings: {} },
    },
    rawResources: { OreIron: { id: 'OreIron', name: 'Iron Ore', amount: 120 } },
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 120, displayOrder: 5 },
      IronScrew: { productId: 'IronScrew', surplus: 0, demands: 0, supply: 90, displayOrder: 4 },
      IronPlate: { productId: 'IronPlate', surplus: 0, demands: 0, supply: 45, displayOrder: 3 },
      IronRod: { productId: 'IronRod', surplus: 0, demands: 0, supply: 52.5, displayOrder: 2 },
      IronPlateReinforced: {
        productId: 'IronPlateReinforced',
        surplus: 0,
        demands: 0,
        supply: 7.5,
        displayOrder: 1,
      },
      ModularFrame: { productId: 'ModularFrame', surplus: 2.5, demands: 2.5, supply: 5, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 6,
    inSync: true,
    syncState: {
      ModularFrame: { amount: 5, recipe: 'ModularFrame' },
      IronPlateReinforced: { amount: 7.5, recipe: 'IronPlateReinforced' },
      IronRod: { amount: 52.5, recipe: 'IronRod' },
      IronPlate: { amount: 45, recipe: 'IronPlate' },
      IronScrew: { amount: 90, recipe: 'Screw' },
      IronIngot: { amount: 120, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 3843,
    name: 'Steel Pipe | Beam | Encased Industrial Beam',
    products: [{
      id: 'SteelPipe',
      amount: 360,
      recipe: 'SteelPipe',
      displayOrder: 0,
      requirements: { SteelIngot: { amount: 540 } },
      buildingRequirements: { name: 'constructormk1', amount: 18, powerPerBuilding: 4, totalPower: 72 },
      byProducts: [],
    }, {
      id: 'SteelPlate',
      amount: 135,
      recipe: 'SteelBeam',
      displayOrder: 1,
      requirements: { SteelIngot: { amount: 540 } },
      buildingRequirements: { name: 'constructormk1', amount: 9, powerPerBuilding: 4, totalPower: 36 },
      byProducts: [],
    }, {
      id: 'SteelPlateReinforced',
      amount: 15,
      recipe: 'EncasedIndustrialBeam',
      displayOrder: 2,
      requirements: { SteelPlate: { amount: 45 }, Cement: { amount: 90 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 2.5,
        powerPerBuilding: 15,
        totalPower: 36.00000039462546,
      },
      byProducts: [],
    }, {
      id: 'Cement',
      amount: 90,
      recipe: 'Concrete',
      displayOrder: 3,
      requirements: { Stone: { amount: 270 } },
      buildingRequirements: { name: 'constructormk1', amount: 6, powerPerBuilding: 4, totalPower: 24 },
      byProducts: [],
    }, {
      id: 'SteelIngot',
      amount: 1080,
      recipe: 'Alternate_IngotSteel_1',
      displayOrder: 4,
      requirements: { IronIngot: { amount: 720 }, Coal: { amount: 720 } },
      buildingRequirements: { name: 'foundrymk1', amount: 18, powerPerBuilding: 16, totalPower: 288 },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 720,
      recipe: 'IngotIron',
      displayOrder: 5,
      requirements: { OreIron: { amount: 720 } },
      buildingRequirements: { name: 'smeltermk1', amount: 24, powerPerBuilding: 4, totalPower: 96 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      SteelIngot: { id: 'SteelIngot', amount: 1080 },
      SteelPlate: { id: 'SteelPlate', amount: 135 },
      Cement: { id: 'Cement', amount: 90 },
      IronIngot: { id: 'IronIngot', amount: 720 },
    },
    inputs: [],
    parts: {},
    buildingRequirements: {
      constructormk1: {
        name: 'constructormk1',
        amount: 33,
        powerPerBuilding: 4,
        totalPower: 168.00000039462546,
      },
      assemblermk1: { name: 'assemblermk1', amount: 2.5, powerPerBuilding: 15, totalPower: 144.00000039462546 },
      foundrymk1: { name: 'foundrymk1', amount: 18, powerPerBuilding: 16, totalPower: 456.00000039462543 },
      smeltermk1: { name: 'smeltermk1', amount: 24, powerPerBuilding: 4, totalPower: 552.0000003946254 },
    },
    totalPower: 552.0000003946254,
    dependencies: {
      requests: {
        3986: [{ requestingFactoryId: 3986, part: 'SteelPipe', amount: 15 }],
        7479: [{ requestingFactoryId: 7479, part: 'SteelPipe', amount: 30 }],
        9463: [{ requestingFactoryId: 9463, part: 'SteelPlate', amount: 30 }],
      },
      metrics: {
        SteelPipe: {
          part: 'SteelPipe',
          request: 45,
          supply: 360,
          isRequestSatisfied: true,
          difference: 315,
        },
        SteelPlate: {
          part: 'SteelPlate',
          request: 30,
          supply: 135,
          isRequestSatisfied: true,
          difference: 105,
        },
      },
    },
    exportCalculator: {
      SteelPipe: { selected: '7479', factorySettings: {} },
      SteelPlate: { selected: '9463', factorySettings: {} },
      SteelPlateReinforced: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
      SteelIngot: { selected: null, factorySettings: {} },
      Cement: { selected: null, factorySettings: {} },
    },
    rawResources: {},
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 720, displayOrder: 5 },
      SteelIngot: { productId: 'SteelIngot', surplus: 0, demands: 0, supply: 1080, displayOrder: 4 },
      Cement: { productId: 'Cement', surplus: 0, demands: 0, supply: 90, displayOrder: 3 },
      SteelPlateReinforced: {
        productId: 'SteelPlateReinforced',
        surplus: 15,
        demands: 0,
        supply: 15,
        displayOrder: 2,
      },
      SteelPlate: { productId: 'SteelPlate', surplus: 60, demands: 30, supply: 135, displayOrder: 1 },
      SteelPipe: { productId: 'SteelPipe', surplus: 315, demands: 45, supply: 360, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: false,
    hasProblem: false,
    displayOrder: 7,
    inSync: true,
    syncState: {
      SteelPipe: { amount: 360, recipe: 'SteelPipe' },
      SteelPlate: { amount: 135, recipe: 'SteelBeam' },
      SteelPlateReinforced: { amount: 15, recipe: 'EncasedIndustrialBeam' },
      Cement: { amount: 90, recipe: 'Concrete' },
      SteelIngot: { amount: 1080, recipe: 'Alternate_IngotSteel_1' },
      IronIngot: { amount: 720, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 9463,
    name: 'Versatile Framework',
    products: [{
      id: 'SpaceElevatorPart_2',
      amount: 5,
      recipe: 'SpaceElevatorPart_2',
      displayOrder: 0,
      requirements: { ModularFrame: { amount: 2.5 }, SteelPlate: { amount: 30 } },
      buildingRequirements: { name: 'assemblermk1', amount: 1, powerPerBuilding: 15, totalPower: 15 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {},
    inputs: [{ factoryId: 5073, outputPart: 'ModularFrame', amount: 2.5 }, {
      factoryId: 3843,
      outputPart: 'SteelPlate',
      amount: 30,
    }],
    parts: {
      ModularFrame: {
        amountRequired: 2.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 2.5,
        amountSupplied: 2.5,
        amountSuppliedViaInput: 2.5,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      SteelPlate: {
        amountRequired: 30,
        amountRequiredExports: 0,
        amountRequiredProduction: 30,
        amountSupplied: 30,
        amountSuppliedViaInput: 30,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      SpaceElevatorPart_2: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 5,
        amountRemaining: 5,
        satisfied: true,
        isRaw: false,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 1,
        powerPerBuilding: 15,
        totalPower: 15,
      },
    },
    totalPower: 15,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: { SpaceElevatorPart_2: { selected: null, factorySettings: {} } },
    rawResources: {},
    exports: {
      SpaceElevatorPart_2: {
        productId: 'SpaceElevatorPart_2',
        surplus: 5,
        demands: 0,
        supply: 5,
        displayOrder: 0,
      },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 8,
    inSync: true,
    syncState: { SpaceElevatorPart_2: { amount: 5, recipe: 'SpaceElevatorPart_2' } },
    tasks: [],
    notes: '',
  }, {
    id: 3986,
    name: 'Automated Wiring',
    products: [{
      id: 'SpaceElevatorPart_3',
      amount: 5,
      recipe: 'SpaceElevatorPart_3',
      displayOrder: 0,
      requirements: { Stator: { amount: 5 }, Cable: { amount: 100 } },
      buildingRequirements: { name: 'assemblermk1', amount: 2, powerPerBuilding: 15, totalPower: 30 },
      byProducts: [],
    }, {
      id: 'Stator',
      amount: 5,
      recipe: 'Stator',
      displayOrder: 1,
      requirements: { SteelPipe: { amount: 15 }, Wire: { amount: 40 } },
      buildingRequirements: { name: 'assemblermk1', amount: 1, powerPerBuilding: 15, totalPower: 15 },
      byProducts: [],
    }, {
      id: 'Cable',
      amount: 100,
      recipe: 'Cable',
      displayOrder: 2,
      requirements: { Wire: { amount: 200 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 3.3333333333333335,
        powerPerBuilding: 4,
        totalPower: 12.936138367958613,
      },
      byProducts: [],
    }, {
      id: 'Wire',
      amount: 240,
      recipe: 'Wire',
      displayOrder: 3,
      requirements: { CopperIngot: { amount: 120 } },
      buildingRequirements: { name: 'constructormk1', amount: 8, powerPerBuilding: 4, totalPower: 32 },
      byProducts: [],
    }, {
      id: 'CopperIngot',
      amount: 120,
      recipe: 'IngotCopper',
      displayOrder: 4,
      requirements: { OreCopper: { amount: 120 } },
      buildingRequirements: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 16 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      Stator: { id: 'Stator', amount: 5 },
      Cable: { id: 'Cable', amount: 100 },
      Wire: { id: 'Wire', amount: 240 },
      CopperIngot: { id: 'CopperIngot', amount: 120 },
    },
    inputs: [{ factoryId: 3843, outputPart: 'SteelPipe', amount: 15 }],
    parts: {
      SteelPipe: {
        amountRequired: 15,
        amountRequiredExports: 0,
        amountRequiredProduction: 15,
        amountSupplied: 15,
        amountSuppliedViaInput: 15,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      SpaceElevatorPart_3: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 5,
        amountRemaining: 5,
        satisfied: true,
        isRaw: false,
      },
      Stator: {
        amountRequired: 5,
        amountRequiredExports: 0,
        amountRequiredProduction: 5,
        amountSupplied: 5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Cable: {
        amountRequired: 100,
        amountRequiredExports: 0,
        amountRequiredProduction: 100,
        amountSupplied: 100,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 100,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Wire: {
        amountRequired: 240,
        amountRequiredExports: 0,
        amountRequiredProduction: 240,
        amountSupplied: 240,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 240,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      CopperIngot: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 120,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreCopper: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountSupplied: 120,
        amountSuppliedViaInput: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 3,
        powerPerBuilding: 15,
        totalPower: 45,
      },
      constructormk1: {
        name: 'constructormk1',
        amount: 11.333333333333334,
        powerPerBuilding: 4,
        totalPower: 89.93613836795862,
      },
      smeltermk1: { name: 'smeltermk1', amount: 4, powerPerBuilding: 4, totalPower: 105.93613836795862 },
    },
    totalPower: 105.93613836795862,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {
      SpaceElevatorPart_3: { selected: null, factorySettings: {} },
      CopperIngot: { selected: null, factorySettings: {} },
      Wire: { selected: null, factorySettings: {} },
      Cable: { selected: null, factorySettings: {} },
      Stator: { selected: null, factorySettings: {} },
    },
    rawResources: { OreCopper: { id: 'OreCopper', name: 'Copper Ore', amount: 120 } },
    exports: {
      CopperIngot: {
        productId: 'CopperIngot',
        surplus: 0,
        demands: 0,
        supply: 120,
        displayOrder: 4,
      },
      Wire: { productId: 'Wire', surplus: 0, demands: 0, supply: 240, displayOrder: 3 },
      Cable: { productId: 'Cable', surplus: 0, demands: 0, supply: 100, displayOrder: 2 },
      Stator: { productId: 'Stator', surplus: 0, demands: 0, supply: 5, displayOrder: 1 },
      SpaceElevatorPart_3: {
        productId: 'SpaceElevatorPart_3',
        surplus: 5,
        demands: 0,
        supply: 5,
        displayOrder: 0,
      },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 9,
    inSync: true,
    syncState: {
      SpaceElevatorPart_3: { amount: 5, recipe: 'SpaceElevatorPart_3' },
      Stator: { amount: 5, recipe: 'Stator' },
      Cable: { amount: 100, recipe: 'Cable' },
      Wire: { amount: 240, recipe: 'Wire' },
      CopperIngot: { amount: 120, recipe: 'IngotCopper' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 6836,
    name: 'Quickwire',
    products: [{
      id: 'HighSpeedWire',
      amount: 450,
      recipe: 'Quickwire',
      displayOrder: 0,
      requirements: { GoldIngot: { amount: 90 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 7.5,
        powerPerBuilding: 4,
        totalPower: 29.600000105233455,
      },
      byProducts: [],
    }, {
      id: 'GoldIngot',
      amount: 90,
      recipe: 'IngotCaterium',
      displayOrder: 1,
      requirements: { OreGold: { amount: 270 } },
      buildingRequirements: { name: 'smeltermk1', amount: 6, powerPerBuilding: 4, totalPower: 24 },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: { GoldIngot: { id: 'GoldIngot', amount: 90 } },
    inputs: [],
    parts: {
      HighSpeedWire: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 450,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 450,
        amountRemaining: 450,
        satisfied: true,
        isRaw: false,
      },
      GoldIngot: {
        amountRequired: 90,
        amountRequiredExports: 0,
        amountRequiredProduction: 90,
        amountSupplied: 90,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 90,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreGold: {
        amountRequired: 270,
        amountRequiredExports: 0,
        amountRequiredProduction: 270,
        amountSupplied: 270,
        amountSuppliedViaInput: 270,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      constructormk1: {
        name: 'constructormk1',
        amount: 7.5,
        powerPerBuilding: 4,
        totalPower: 29.600000105233455,
      },
      smeltermk1: { name: 'smeltermk1', amount: 6, powerPerBuilding: 4, totalPower: 53.600000105233455 },
    },
    totalPower: 53.600000105233455,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {
      HighSpeedWire: { selected: null, factorySettings: {} },
      GoldIngot: { selected: null, factorySettings: {} },
    },
    rawResources: { OreGold: { id: 'OreGold', name: 'Caterium Ore', amount: 270 } },
    exports: {
      GoldIngot: { productId: 'GoldIngot', surplus: 0, demands: 0, supply: 90, displayOrder: 1 },
      HighSpeedWire: { productId: 'HighSpeedWire', surplus: 450, demands: 0, supply: 450, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    displayOrder: 10,
    inSync: true,
    syncState: {
      HighSpeedWire: { amount: 450, recipe: 'Quickwire' },
      GoldIngot: { amount: 90, recipe: 'IngotCaterium' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 7479,
    name: 'Motor',
    products: [{
      id: 'Motor',
      amount: 5,
      recipe: 'Motor',
      displayOrder: 0,
      requirements: { Rotor: { amount: 10 }, Stator: { amount: 10 } },
      buildingRequirements: { name: 'assemblermk1', amount: 1, powerPerBuilding: 15, totalPower: 15 },
      byProducts: [],
    }, {
      id: 'Rotor',
      amount: 10,
      recipe: 'Rotor',
      displayOrder: 1,
      requirements: { IronRod: { amount: 50 }, IronScrew: { amount: 250 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 2.5,
        powerPerBuilding: 15,
        totalPower: 36.00000039462546,
      },
      byProducts: [],
    }, {
      id: 'Stator',
      amount: 10,
      recipe: 'Stator',
      displayOrder: 2,
      requirements: { SteelPipe: { amount: 30 }, Wire: { amount: 80 } },
      buildingRequirements: { name: 'assemblermk1', amount: 2, powerPerBuilding: 15, totalPower: 30 },
      byProducts: [],
    }, {
      id: 'Wire',
      amount: 80,
      recipe: 'Wire',
      displayOrder: 3,
      requirements: { CopperIngot: { amount: 40 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 2.6666666666666665,
        powerPerBuilding: 4,
        totalPower: 10.340345765969857,
      },
      byProducts: [],
    }, {
      id: 'IronRod',
      amount: 112.5,
      recipe: 'IronRod',
      displayOrder: 4,
      requirements: { IronIngot: { amount: 112.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 7.5,
        powerPerBuilding: 4,
        totalPower: 29.600000105233455,
      },
      byProducts: [],
    }, {
      id: 'IronScrew',
      amount: 250,
      recipe: 'Screw',
      displayOrder: 5,
      requirements: { IronRod: { amount: 62.5 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 6.25,
        powerPerBuilding: 4,
        totalPower: 24.640000084186767,
      },
      byProducts: [],
    }, {
      id: 'CopperIngot',
      amount: 40,
      recipe: 'IngotCopper',
      displayOrder: 6,
      requirements: { OreCopper: { amount: 40 } },
      buildingRequirements: {
        name: 'smeltermk1',
        amount: 1.3333333333333333,
        powerPerBuilding: 4,
        totalPower: 4.936138367958612,
      },
      byProducts: [],
    }, {
      id: 'IronIngot',
      amount: 112.5,
      recipe: 'IngotIron',
      displayOrder: 7,
      requirements: { OreIron: { amount: 112.5 } },
      buildingRequirements: {
        name: 'smeltermk1',
        amount: 3.75,
        powerPerBuilding: 4,
        totalPower: 14.73463883584809,
      },
      byProducts: [],
    }],
    byProducts: [],
    internalProducts: {
      Rotor: { id: 'Rotor', amount: 10 },
      Stator: { id: 'Stator', amount: 10 },
      IronRod: { id: 'IronRod', amount: 112.5 },
      IronScrew: { id: 'IronScrew', amount: 250 },
      Wire: { id: 'Wire', amount: 80 },
      CopperIngot: { id: 'CopperIngot', amount: 40 },
      IronIngot: { id: 'IronIngot', amount: 112.5 },
    },
    inputs: [{ factoryId: 3843, outputPart: 'SteelPipe', amount: 30 }],
    parts: {
      SteelPipe: {
        amountRequired: 30,
        amountRequiredExports: 0,
        amountRequiredProduction: 30,
        amountSupplied: 30,
        amountSuppliedViaInput: 30,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Motor: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountSupplied: 5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 5,
        amountRemaining: 5,
        satisfied: true,
        isRaw: false,
      },
      Rotor: {
        amountRequired: 10,
        amountRequiredExports: 0,
        amountRequiredProduction: 10,
        amountSupplied: 10,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 10,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Stator: {
        amountRequired: 10,
        amountRequiredExports: 0,
        amountRequiredProduction: 10,
        amountSupplied: 10,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 10,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronRod: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 112.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronScrew: {
        amountRequired: 250,
        amountRequiredExports: 0,
        amountRequiredProduction: 250,
        amountSupplied: 250,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 250,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      Wire: {
        amountRequired: 80,
        amountRequiredExports: 0,
        amountRequiredProduction: 80,
        amountSupplied: 80,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 80,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      CopperIngot: {
        amountRequired: 40,
        amountRequiredExports: 0,
        amountRequiredProduction: 40,
        amountSupplied: 40,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 40,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      IronIngot: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaProduction: 112.5,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
      },
      OreCopper: {
        amountRequired: 40,
        amountRequiredExports: 0,
        amountRequiredProduction: 40,
        amountSupplied: 40,
        amountSuppliedViaInput: 40,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
      OreIron: {
        amountRequired: 112.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 112.5,
        amountSupplied: 112.5,
        amountSuppliedViaInput: 112.5,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
      },
    },
    buildingRequirements: {
      assemblermk1: {
        name: 'assemblermk1',
        amount: 5.5,
        powerPerBuilding: 15,
        totalPower: 81.00000039462546,
      },
      constructormk1: {
        name: 'constructormk1',
        amount: 16.416666666666664,
        powerPerBuilding: 4,
        totalPower: 145.58034635001553,
      },
      smeltermk1: {
        name: 'smeltermk1',
        amount: 5.083333333333333,
        powerPerBuilding: 4,
        totalPower: 165.25112355382225,
      },
    },
    totalPower: 165.25112355382225,
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {
      Motor: { selected: null, factorySettings: {} },
      IronIngot: { selected: null, factorySettings: {} },
      CopperIngot: { selected: null, factorySettings: {} },
      IronScrew: { selected: null, factorySettings: {} },
      IronRod: { selected: null, factorySettings: {} },
      Wire: { selected: null, factorySettings: {} },
      Stator: { selected: null, factorySettings: {} },
      Rotor: { selected: null, factorySettings: {} },
    },
    rawResources: {
      OreCopper: { id: 'OreCopper', name: 'Copper Ore', amount: 40 },
      OreIron: { id: 'OreIron', name: 'Iron Ore', amount: 112.5 },
    },
    exports: {
      IronIngot: { productId: 'IronIngot', surplus: 0, demands: 0, supply: 112.5, displayOrder: 7 },
      CopperIngot: { productId: 'CopperIngot', surplus: 0, demands: 0, supply: 40, displayOrder: 6 },
      IronScrew: { productId: 'IronScrew', surplus: 0, demands: 0, supply: 250, displayOrder: 5 },
      IronRod: { productId: 'IronRod', surplus: 0, demands: 0, supply: 112.5, displayOrder: 4 },
      Wire: { productId: 'Wire', surplus: 0, demands: 0, supply: 80, displayOrder: 3 },
      Stator: { productId: 'Stator', surplus: 0, demands: 0, supply: 10, displayOrder: 2 },
      Rotor: { productId: 'Rotor', surplus: 0, demands: 0, supply: 10, displayOrder: 1 },
      Motor: { productId: 'Motor', surplus: 5, demands: 0, supply: 5, displayOrder: 0 },
    },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: false,
    hasProblem: false,
    displayOrder: 11,
    inSync: true,
    syncState: {
      Motor: { amount: 5, recipe: 'Motor' },
      Rotor: { amount: 10, recipe: 'Rotor' },
      Stator: { amount: 10, recipe: 'Stator' },
      Wire: { amount: 80, recipe: 'Wire' },
      IronRod: { amount: 112.5, recipe: 'IronRod' },
      IronScrew: { amount: 250, recipe: 'Screw' },
      CopperIngot: { amount: 40, recipe: 'IngotCopper' },
      IronIngot: { amount: 112.5, recipe: 'IngotIron' },
    },
    tasks: [],
    notes: '',
  }, {
    id: 7213,
    name: 'Rubber | Plastic | Fuel [Power]',
    products: [{
      id: 'Rubber',
      amount: 100,
      recipe: 'Rubber',
      displayOrder: 0,
      requirements: { LiquidOil: { amount: 150 } },
      buildingRequirements: { name: 'oilrefinery', amount: 5, powerConsumed: 150 },
      byProducts: [{ id: 'HeavyOilResidue', byProductOf: 'Rubber', amount: 100 }],
    }, {
      id: 'Plastic',
      amount: 100,
      recipe: 'Plastic',
      displayOrder: 1,
      requirements: { LiquidOil: { amount: 150 } },
      buildingRequirements: { name: 'oilrefinery', amount: 5, powerConsumed: 150 },
      byProducts: [{ id: 'HeavyOilResidue', byProductOf: 'Plastic', amount: 50 }],
    }, {
      id: 'FluidCanister',
      amount: 20,
      recipe: 'FluidCanister',
      displayOrder: 2,
      requirements: { Plastic: { amount: 10 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 0.3333333333333333,
        powerConsumed: 0.9361383679586117,
      },
      byProducts: [],
    }, {
      id: 'LiquidFuel',
      amount: 100,
      recipe: 'ResidualFuel',
      displayOrder: 3,
      requirements: { HeavyOilResidue: { amount: 150 } },
      buildingRequirements: { name: 'oilrefinery', amount: 2.5, powerConsumed: 72.00000078925092 },
      byProducts: [],
    }, {
      id: 'Fuel',
      amount: 20,
      recipe: 'Fuel',
      displayOrder: 4,
      requirements: { LiquidFuel: { amount: 20 }, FluidCanister: { amount: 20 } },
      buildingRequirements: { name: 'packager', amount: 0.5, powerConsumed: 4.000000263083639 },
      byProducts: [],
    }],
    byProducts: [{ id: 'HeavyOilResidue', amount: 150, byProductOf: 'Rubber' }],
    powerProducers: [{
      building: 'generatorfuel',
      buildingAmount: 4,
      buildingCount: 4,
      ingredientAmount: 80,
      ingredients: [{ part: 'LiquidFuel', perMin: 80, mwPerItem: 12.5 }],
      powerAmount: 1000,
      powerProduced: 1000,
      recipe: 'GeneratorFuel_LiquidFuel',
      byproduct: null,
      displayOrder: 0,
      updated: 'ingredient',
    }],
    inputs: [],
    previousInputs: [],
    parts: {
      Rubber: {
        amountRequired: 37.5,
        amountRequiredExports: 37.5,
        amountRequiredProduction: 0,
        amountRequiredPower: 0,
        amountSupplied: 100,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 100,
        amountRemaining: 62.5,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      LiquidOil: {
        amountRequired: 300,
        amountRequiredExports: 0,
        amountRequiredProduction: 300,
        amountRequiredPower: 0,
        amountSupplied: 300,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 300,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
        exportable: false,
      },
      Plastic: {
        amountRequired: 74,
        amountRequiredExports: 64,
        amountRequiredProduction: 10,
        amountRequiredPower: 0,
        amountSupplied: 100,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 100,
        amountRemaining: 26,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      FluidCanister: {
        amountRequired: 20,
        amountRequiredExports: 0,
        amountRequiredProduction: 20,
        amountRequiredPower: 0,
        amountSupplied: 20,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 20,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      LiquidFuel: {
        amountRequired: 100,
        amountRequiredExports: 0,
        amountRequiredProduction: 20,
        amountRequiredPower: 80,
        amountSupplied: 100,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 100,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      HeavyOilResidue: {
        amountRequired: 150,
        amountRequiredExports: 0,
        amountRequiredProduction: 150,
        amountRequiredPower: 0,
        amountSupplied: 150,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 150,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Fuel: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountRequiredPower: 0,
        amountSupplied: 20,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 20,
        amountRemaining: 20,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
    },
    buildingRequirements: {
      oilrefinery: { name: 'oilrefinery', amount: 13, powerConsumed: 372 },
      constructormk1: { name: 'constructormk1', amount: 1, powerConsumed: 0.936 },
      packager: { name: 'packager', amount: 1, powerConsumed: 4 },
      generatorfuel: { name: 'generatorfuel', amount: 4, powerProduced: 1000 },
    },
    dependencies: {
      requests: {
        1356: [{ requestingFactoryId: 1356, part: 'Plastic', amount: 64 }],
        9357: [{ requestingFactoryId: 9357, part: 'Rubber', amount: 37.5 }],
      },
      metrics: {
        Plastic: {
          part: 'Plastic',
          request: 64,
          supply: 100,
          isRequestSatisfied: true,
          difference: 36,
        },
        Rubber: { part: 'Rubber', request: 37.5, supply: 100, isRequestSatisfied: true, difference: 62.5 },
      },
    },
    exportCalculator: {},
    rawResources: { LiquidOil: { id: 'LiquidOil', name: 'Crude Oil', amount: 300 } },
    power: { consumed: 376.936, produced: 1000, difference: 623.0640000000001 },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    inSync: true,
    syncState: {
      Rubber: { amount: 100, recipe: 'Rubber' },
      Plastic: { amount: 100, recipe: 'Plastic' },
      FluidCanister: { amount: 20, recipe: 'FluidCanister' },
      LiquidFuel: { amount: 100, recipe: 'ResidualFuel' },
      Fuel: { amount: 20, recipe: 'Fuel' },
    },
    displayOrder: 13,
    tasks: [],
    notes: '',
  }, {
    id: 9826,
    name: 'Gunpowder',
    products: [{
      id: 'NobeliskExplosive',
      amount: 20,
      recipe: 'Nobelisk',
      displayOrder: 0,
      requirements: { Gunpowder: { amount: 40 }, SteelPipe: { amount: 40 } },
      buildingRequirements: { name: 'assemblermk1', amount: 2, powerConsumed: 30 },
      byProducts: [],
    }, {
      id: 'Gunpowder',
      amount: 240,
      recipe: 'Gunpowder',
      displayOrder: 1,
      requirements: { Coal: { amount: 120 }, Sulfur: { amount: 120 } },
      buildingRequirements: { name: 'assemblermk1', amount: 8, powerConsumed: 120 },
      byProducts: [],
    }],
    byProducts: [],
    powerProducers: [],
    inputs: [],
    previousInputs: [],
    parts: {
      NobeliskExplosive: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountRequiredPower: 0,
        amountSupplied: 20,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 20,
        amountRemaining: 20,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Gunpowder: {
        amountRequired: 40,
        amountRequiredExports: 0,
        amountRequiredProduction: 40,
        amountRequiredPower: 0,
        amountSupplied: 240,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 240,
        amountRemaining: 200,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      SteelPipe: {
        amountRequired: 40,
        amountRequiredExports: 0,
        amountRequiredProduction: 40,
        amountRequiredPower: 0,
        amountSupplied: 0,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 0,
        amountRemaining: -40,
        satisfied: false,
        isRaw: false,
        exportable: false,
      },
      Coal: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountRequiredPower: 0,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
        exportable: false,
      },
      Sulfur: {
        amountRequired: 120,
        amountRequiredExports: 0,
        amountRequiredProduction: 120,
        amountRequiredPower: 0,
        amountSupplied: 120,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 120,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
        exportable: false,
      },
    },
    buildingRequirements: { assemblermk1: { name: 'assemblermk1', amount: 10, powerConsumed: 150 } },
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {},
    rawResources: {
      Coal: { id: 'Coal', name: 'Coal', amount: 120 },
      Sulfur: { id: 'Sulfur', name: 'Sulfur', amount: 120 },
    },
    power: { consumed: 150, produced: 0, difference: -150 },
    requirementsSatisfied: false,
    usingRawResourcesOnly: false,
    hidden: false,
    hasProblem: true,
    inSync: false,
    syncState: {
      NobeliskExplosive: { amount: 20, recipe: 'Nobelisk' },
      Gunpowder: { amount: 240, recipe: 'Gunpowder' },
    },
    displayOrder: 14,
    tasks: [],
    notes: '',
  }, {
    id: 1356,
    name: 'Circuit Board | High-Speed Connector',
    products: [{
      id: 'HighSpeedConnector',
      amount: 8,
      recipe: 'HighSpeedConnector',
      displayOrder: 0,
      requirements: { HighSpeedWire: { amount: 448 }, Cable: { amount: 80 }, CircuitBoard: { amount: 8 } },
      buildingRequirements: {
        name: 'manufacturermk1',
        amount: 2.1333333333333333,
        powerConsumed: 113.83349325717178,
      },
      byProducts: [],
    }, {
      id: 'CircuitBoard',
      amount: 16,
      recipe: 'CircuitBoard',
      displayOrder: 1,
      requirements: { CopperSheet: { amount: 32 }, Plastic: { amount: 64 } },
      buildingRequirements: {
        name: 'assemblermk1',
        amount: 2.1333333333333333,
        powerConsumed: 31.04549816104685,
      },
      byProducts: [],
    }, {
      id: 'Cable',
      amount: 80,
      recipe: 'Cable',
      displayOrder: 2,
      requirements: { Wire: { amount: 160 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 2.6666666666666665,
        powerConsumed: 10.340345765969857,
      },
      byProducts: [],
    }, {
      id: 'CopperSheet',
      amount: 32,
      recipe: 'CopperSheet',
      displayOrder: 3,
      requirements: { CopperIngot: { amount: 64 } },
      buildingRequirements: { name: 'constructormk1', amount: 3.2, powerConsumed: 12.476509947660588 },
      byProducts: [],
    }, {
      id: 'Wire',
      amount: 160,
      recipe: 'Wire',
      displayOrder: 4,
      requirements: { CopperIngot: { amount: 80 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 5.333333333333333,
        powerConsumed: 20.93613836795861,
      },
      byProducts: [],
    }, {
      id: 'CopperIngot',
      amount: 144,
      recipe: 'IngotCopper',
      displayOrder: 5,
      requirements: { OreCopper: { amount: 144 } },
      buildingRequirements: { name: 'smeltermk1', amount: 4.8, powerConsumed: 18.97818678112255 },
      byProducts: [],
    }, {
      id: 'HighSpeedWire',
      amount: 448,
      recipe: 'Quickwire',
      displayOrder: 6,
      requirements: { GoldIngot: { amount: 89.6 } },
      buildingRequirements: {
        name: 'constructormk1',
        amount: 7.466666666666667,
        powerConsumed: 29.460531026537225,
      },
      byProducts: [],
    }, {
      id: 'GoldIngot',
      amount: 89.6,
      recipe: 'IngotCaterium',
      displayOrder: 7,
      requirements: { OreGold: { amount: 268.8 } },
      buildingRequirements: { name: 'smeltermk1', amount: 5.973333333333333, powerConsumed: 23.8596032849972 },
      byProducts: [],
    }],
    byProducts: [],
    powerProducers: [],
    inputs: [{ factoryId: 7213, outputPart: 'Plastic', amount: 64 }],
    previousInputs: [{ factoryId: 7213, outputPart: null, amount: 0 }],
    parts: {
      HighSpeedConnector: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountRequiredPower: 0,
        amountSupplied: 8,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 8,
        amountRemaining: 8,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      HighSpeedWire: {
        amountRequired: 448,
        amountRequiredExports: 0,
        amountRequiredProduction: 448,
        amountRequiredPower: 0,
        amountSupplied: 448,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 448,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Cable: {
        amountRequired: 80,
        amountRequiredExports: 0,
        amountRequiredProduction: 80,
        amountRequiredPower: 0,
        amountSupplied: 80,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 80,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      CircuitBoard: {
        amountRequired: 8,
        amountRequiredExports: 0,
        amountRequiredProduction: 8,
        amountRequiredPower: 0,
        amountSupplied: 16,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 16,
        amountRemaining: 8,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      CopperSheet: {
        amountRequired: 32,
        amountRequiredExports: 0,
        amountRequiredProduction: 32,
        amountRequiredPower: 0,
        amountSupplied: 32,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 32,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Plastic: {
        amountRequired: 64,
        amountRequiredExports: 0,
        amountRequiredProduction: 64,
        amountRequiredPower: 0,
        amountSupplied: 64,
        amountSuppliedViaInput: 64,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: false,
      },
      CopperIngot: {
        amountRequired: 144,
        amountRequiredExports: 0,
        amountRequiredProduction: 144,
        amountRequiredPower: 0,
        amountSupplied: 144,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 144,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Wire: {
        amountRequired: 160,
        amountRequiredExports: 0,
        amountRequiredProduction: 160,
        amountRequiredPower: 0,
        amountSupplied: 160,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 160,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      OreCopper: {
        amountRequired: 144,
        amountRequiredExports: 0,
        amountRequiredProduction: 144,
        amountRequiredPower: 0,
        amountSupplied: 144,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 144,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
        exportable: false,
      },
      GoldIngot: {
        amountRequired: 89.6,
        amountRequiredExports: 0,
        amountRequiredProduction: 89.6,
        amountRequiredPower: 0,
        amountSupplied: 89.6,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 89.6,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      OreGold: {
        amountRequired: 268.8,
        amountRequiredExports: 0,
        amountRequiredProduction: 268.8,
        amountRequiredPower: 0,
        amountSupplied: 268.8,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 268.8,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: true,
        exportable: false,
      },
    },
    buildingRequirements: {
      manufacturermk1: { name: 'manufacturermk1', amount: 3, powerConsumed: 113.833 },
      assemblermk1: { name: 'assemblermk1', amount: 3, powerConsumed: 31.045 },
      constructormk1: { name: 'constructormk1', amount: 21, powerConsumed: 73.214 },
      smeltermk1: { name: 'smeltermk1', amount: 11, powerConsumed: 42.838 },
    },
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {},
    rawResources: {
      OreCopper: { id: 'OreCopper', name: 'Copper Ore', amount: 144 },
      OreGold: { id: 'OreGold', name: 'Caterium Ore', amount: 268.8 },
    },
    power: { consumed: 260.93, produced: 0, difference: -260.93 },
    requirementsSatisfied: true,
    usingRawResourcesOnly: false,
    hidden: true,
    hasProblem: false,
    inSync: true,
    syncState: {
      HighSpeedConnector: { amount: 8, recipe: 'HighSpeedConnector' },
      CircuitBoard: { amount: 16, recipe: 'CircuitBoard' },
      Cable: { amount: 80, recipe: 'Cable' },
      CopperSheet: { amount: 32, recipe: 'CopperSheet' },
      Wire: { amount: 160, recipe: 'Wire' },
      CopperIngot: { amount: 144, recipe: 'IngotCopper' },
      HighSpeedWire: { amount: 448, recipe: 'Quickwire' },
      GoldIngot: { amount: 89.6, recipe: 'IngotCaterium' },
    },
    displayOrder: 14,
    tasks: [],
    notes: '',
  }, {
    id: 9357,
    name: 'Modular Engine',
    products: [{
      id: 'SpaceElevatorPart_4',
      amount: 2.5,
      recipe: 'SpaceElevatorPart_4',
      displayOrder: 0,
      requirements: { Motor: { amount: 5 }, Rubber: { amount: 37.5 }, SpaceElevatorPart_1: { amount: 5 } },
      buildingRequirements: { name: 'manufacturermk1', amount: 2.5, powerConsumed: 132.00000144696003 },
      byProducts: [],
    }],
    byProducts: [],
    powerProducers: [],
    inputs: [{ factoryId: 7213, outputPart: 'Rubber', amount: 37.5 }],
    previousInputs: [{ factoryId: 7213, outputPart: null, amount: 0 }],
    parts: {
      SpaceElevatorPart_4: {
        amountRequired: 0,
        amountRequiredExports: 0,
        amountRequiredProduction: 0,
        amountRequiredPower: 0,
        amountSupplied: 2.5,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 2.5,
        amountRemaining: 2.5,
        satisfied: true,
        isRaw: false,
        exportable: true,
      },
      Motor: {
        amountRequired: 5,
        amountRequiredExports: 0,
        amountRequiredProduction: 5,
        amountRequiredPower: 0,
        amountSupplied: 0,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 0,
        amountRemaining: -5,
        satisfied: false,
        isRaw: false,
        exportable: false,
      },
      Rubber: {
        amountRequired: 37.5,
        amountRequiredExports: 0,
        amountRequiredProduction: 37.5,
        amountRequiredPower: 0,
        amountSupplied: 37.5,
        amountSuppliedViaInput: 37.5,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 0,
        amountRemaining: 0,
        satisfied: true,
        isRaw: false,
        exportable: false,
      },
      SpaceElevatorPart_1: {
        amountRequired: 5,
        amountRequiredExports: 0,
        amountRequiredProduction: 5,
        amountRequiredPower: 0,
        amountSupplied: 0,
        amountSuppliedViaInput: 0,
        amountSuppliedViaRaw: 0,
        amountSuppliedViaProduction: 0,
        amountRemaining: -5,
        satisfied: false,
        isRaw: false,
        exportable: false,
      },
    },
    buildingRequirements: { manufacturermk1: { name: 'manufacturermk1', amount: 3, powerConsumed: 132 } },
    dependencies: { requests: {}, metrics: {} },
    exportCalculator: {},
    rawResources: {},
    power: { consumed: 132, produced: 0, difference: -132 },
    requirementsSatisfied: false,
    usingRawResourcesOnly: false,
    hidden: false,
    hasProblem: true,
    inSync: null,
    syncState: {},
    displayOrder: 15,
    tasks: [],
    notes: '',
  }]
}
