/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    FactoryDebug: typeof import('./components/FactoryDebug.vue')['default']
    FactoryNode: typeof import('./components/graph/FactoryNode.vue')['default']
    FactoryProduct: typeof import('./components/planner/products/FactoryProduct.vue')['default']
    GameAsset: typeof import('./components/GameAsset.vue')['default']
    Graph: typeof import('./components/graph/Graph.vue')['default']
    Introduction: typeof import('./components/planner/Introduction.vue')['default']
    JoinDiscord: typeof import('./components/JoinDiscord.vue')['default']
    KoFi: typeof import('./components/ko-fi.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Notice: typeof import('./components/planner/Notice.vue')['default']
    Planner: typeof import('./components/planner/Planner.vue')['default']
    PlannerFactory: typeof import('./components/planner/PlannerFactory.vue')['default']
    PlannerFactoryExportCalculator: typeof import('./components/planner/PlannerFactoryExportCalculator.vue')['default']
    PlannerFactoryImports: typeof import('./components/planner/PlannerFactoryImports.vue')['default']
    PlannerFactoryList: typeof import('./components/planner/PlannerFactoryList.vue')['default']
    PlannerFactoryNotes: typeof import('./components/planner/PlannerFactoryNotes.vue')['default']
    PlannerFactoryPowerProducer: typeof import('./components/planner/products/PlannerFactoryPowerProducer.vue')['default']
    PlannerFactoryProduct: typeof import('./components/planner/products/PlannerFactoryProduct.vue')['default']
    PlannerFactoryProducts: typeof import('./components/planner/products/PlannerFactoryProducts.vue')['default']
    PlannerFactorySatisfaction: typeof import('./components/planner/PlannerFactorySatisfaction.vue')['default']
    PlannerFactorySatisfactionBuildings: typeof import('./components/planner/PlannerFactorySatisfactionBuildings.vue')['default']
    PlannerFactorySatisfactionItems: typeof import('./components/planner/PlannerFactorySatisfactionItems.vue')['default']
    PlannerFactoryTodos: typeof import('./components/planner/PlannerFactoryTodos.vue')['default']
    PlannerGlobalActions: typeof import('./components/planner/PlannerGlobalActions.vue')['default']
    PlannerStatistics: typeof import('./components/planner/PlannerStatistics.vue')['default']
    PowerProducer: typeof import('./components/planner/products/PowerProducer.vue')['default']
    Product: typeof import('./components/planner/products/Product.vue')['default']
    ProductsAndPower: typeof import('./components/planner/products/ProductsAndPower.vue')['default']
    RecipeItem: typeof import('./components/recipes/RecipeItem.vue')['default']
    Recipes: typeof import('./components/recipes/Recipes.vue')['default']
    RecipeSearchItem: typeof import('./components/recipes/RecipeSearchItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./components/ShareButton.vue')['default']
    Splash: typeof import('./components/Splash.vue')['default']
    Sync: typeof import('./components/Sync.vue')['default']
    TabNavigation: typeof import('./components/TabNavigation.vue')['default']
    Templates: typeof import('./components/Templates.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Todo: typeof import('./components/graph/Todo.vue')['default']
  }
}
