/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Planner: typeof import('./components/Planner.vue')['default']
    PlannerRequests: typeof import('./components/PlannerRequests.vue')['default']
    RecipeItem: typeof import('./components/RecipeItem.vue')['default']
    RecipeSearch: typeof import('./components/RecipeSearch.vue')['default']
    RecipeSearchItem: typeof import('./components/RecipeSearchItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
