/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Planner: typeof import('./components/planner/Planner.vue')['default']
    PlannerFactory: typeof import('./components/planner/PlannerFactory.vue')['default']
    PlannerFactoryExports: typeof import('./components/planner/PlannerFactoryExports.vue')['default']
    PlannerFactoryImports: typeof import('./components/planner/PlannerFactoryImports.vue')['default']
    PlannerFactoryInputs: typeof import('./components/planner/PlannerFactoryInputs.vue')['default']
    PlannerFactoryList: typeof import('./components/planner/PlannerFactoryList.vue')['default']
    PlannerFactoryOutputs: typeof import('./components/planner/PlannerFactoryOutputs.vue')['default']
    PlannerFactoryProducts: typeof import('./components/planner/PlannerFactoryProducts.vue')['default']
    PlannerFactorySatisfaction: typeof import('./components/planner/PlannerFactorySatisfaction.vue')['default']
    PlannerGlobalActions: typeof import('./components/planner/PlannerGlobalActions.vue')['default']
    PlannerProducts: typeof import('./components/planner/PlannerProducts.vue')['default']
    PlannerWorldResources: typeof import('./components/planner/PlannerWorldResources.vue')['default']
    RecipeItem: typeof import('./components/RecipeItem.vue')['default']
    Recipes: typeof import('./components/Recipes.vue')['default']
    RecipeSearch: typeof import('./components/RecipeSearch.vue')['default']
    RecipeSearchItem: typeof import('./components/RecipeSearchItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentedBar: typeof import('./components/SegmentedBar.vue')['default']
    Todo: typeof import('./components/planner/Todo.vue')['default']
  }
}
